/**
 * UG Examine
 * UG Examine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Allocation { 
    id: string;
    course: string;
    staff: string;
    description: string;
    year: number;
    noStudents: number;
    semmester: Allocation.SemmesterEnum;
    modeofExam: Allocation.ModeofExamEnum;
}
export namespace Allocation {
    export type SemmesterEnum = 1 | 2;
    export const SemmesterEnum = {
        NUMBER_1: 1 as SemmesterEnum,
        NUMBER_2: 2 as SemmesterEnum
    };
    export type ModeofExamEnum = 'WRITTEN' | 'ONLINE ONSITE' | 'ONLINE';
    export const ModeofExamEnum = {
        Written: 'WRITTEN' as ModeofExamEnum,
        OnlineOnsite: 'ONLINE ONSITE' as ModeofExamEnum,
        Online: 'ONLINE' as ModeofExamEnum
    };
}


