/**
 * UG Examine
 * UG Examine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Course { 
    id: string;
    code: string;
    campus: Course.CampusEnum;
}
export namespace Course {
    export type CampusEnum = 'legon' | 'accra' | 'distance';
    export const CampusEnum = {
        Legon: 'legon' as CampusEnum,
        Accra: 'accra' as CampusEnum,
        Distance: 'distance' as CampusEnum
    };
}


