/**
 * UG Examine
 * UG Examine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAllocationDto { 
    staffId: string;
    courseId: string;
    description: string;
    year: number;
    noStudents?: number;
    modeOfExams?: CreateAllocationDto.ModeOfExamsEnum;
    semmester: CreateAllocationDto.SemmesterEnum;
}
export namespace CreateAllocationDto {
    export type ModeOfExamsEnum = 'WRITTEN' | 'ONLINE ONSITE' | 'ONLINE';
    export const ModeOfExamsEnum = {
        Written: 'WRITTEN' as ModeOfExamsEnum,
        OnlineOnsite: 'ONLINE ONSITE' as ModeOfExamsEnum,
        Online: 'ONLINE' as ModeOfExamsEnum
    };
    export type SemmesterEnum = 1 | 2;
    export const SemmesterEnum = {
        NUMBER_1: 1 as SemmesterEnum,
        NUMBER_2: 2 as SemmesterEnum
    };
}


